spring.application.name=backend

spring.datasource.url=jdbc:postgresql://192.168.68.144:5432/carrosbd
spring.datasource.username=postgres
spring.datasource.password=sus1999

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect`